### ISSUE TITLE
不能自动播放下一首

### ISSUE THREAD

**Issue by syshut** [Jrohy/QPlayer-WordPress-Plugin#1]
播放列表里两首歌，第一首歌曲结束第二首歌不会自动开始，自动播放的开关都试过了，两种情况下都不能自动播放下一首。

**Comment by Jrohy** [comment]
电脑网页可以自动播下一首，只有手机上无法自动跳转，可能手机端限制了

**Comment by syshut** [comment]
@Jrohy 我试的就是电脑网页不能自动下一首，下载的最新版插件测试的..难道是服务器的问题？我觉得不会吧

**Comment by Jrohy** [comment]
@syshut 检查下歌曲后台配置格式，播放连接是否能播，不行换下歌曲
