### ISSUE TITLE
博主大大，您好，有两个问题。

### ISSUE THREAD

**Issue by smartpippin** [Jrohy/QPlayer-WordPress-Plugin#2]
1、大大，你的网站是不是挂掉了。。o(╯□╰)o
2、真的想问的是我自己的网站用的您的这个播放器，为什么不能够显示音乐播放的进度条呢？
我是用的wordpress建的博客，网址是：minginn.xyz  ，麻烦看看这是怎么回事吧（就是图片中的样子）。(☆▽☆)期待更新更完善的功能，比如歌词显示、换页播放不中断等。
https://img.alicdn.com/imgextra/i1/537808570/TB2e9hEaHDD11BjSszfXXbwoFXa_!!537808570.png

**Comment by Jrohy** [comment]
@smartpippin 网站重装中(32内存重装慢)。。
播放器没有进度条的。可以拖动标题栏快进退
播放不中断要博客实现PJAX,  Wordpress平台有相关插件

**Comment by smartpippin** [comment]
好的，我去找找看，多谢哈
