### ISSUE TITLE
启用插件提示：該外掛並未啟用，因為它會引發嚴重的錯誤。

### ISSUE THREAD

**Issue by susdevlop** [Jrohy/QPlayer-WordPress-Plugin#3]
該外掛並未啟用，因為它會引發嚴重的錯誤。
Fatal error: Cannot redeclare get_netease_music() (previously declared in /home/wwwroot/sushome/wp-content/plugins/netease-music/functions/core.php:116) in /home/wwwroot/sushome/wp-content/plugins/QPlayer/option.php on line 115

**Comment by Jrohy** [comment]
@susdevlop 跟另一个网易云解析器插件冲突了， 建议用非插件版(无网易云音乐解析): https://github.com/Jrohy/QPlayer
