### ISSUE TITLE
插件CSS排版有问题

### ISSUE THREAD

**Issue by LiarOnce** [Jrohy/QPlayer-WordPress-Plugin#4]
看起来像是CSS排版问题，看着有点怪异，位于播放控制位置。
![image](https://cloud.githubusercontent.com/assets/11171892/19219927/b3697260-8e53-11e6-83e5-3d1f75ec89ae.png)

**Comment by Jrohy** [comment]
@LiarOnce 清空下浏览器缓存文件看看，如果还是这样可能被主题的css改变了, 检查下修改的css

**Comment by LiarOnce** [comment]
清空过了，一样有这个问题
还有css没有被修改过

**Comment by Jrohy** [comment]
@LiarOnce 发个网址来看下

**Comment by LiarOnce** [comment]
https://www.liaronceme.gq

**Comment by Jrohy** [comment]
@LiarOnce progress被主题修改了

![qq 20161010165611](https://cloud.githubusercontent.com/assets/12463263/19231143/f9dcf55c-8f0a-11e6-9e09-e64abc0926b3.png)

**Comment by LiarOnce** [comment]
看到了，这个暂时不知道怎么改回来。

**Comment by Jrohy** [comment]
@LiarOnce .progress前面加个限定

**Comment by LiarOnce** [comment]
我找不到在哪里改 （/TДT)/

**Comment by LiarOnce** [comment]
解决了，原来的主题没法用pjax，换了个就好了。
